databases:
  - name: study_time_record
    databaseName: study_time_record
    user: aono
    region: singapore

services:
  - type: web
    name: study_time_record
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: study_time_record
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
