- 小さいことを積み重ねる事が、とんでもないところへ行くただひとつの道だと思っています。  イチロー
- 結果が出ない時、どういう自分でいられるか。決して諦めない姿勢が、何かを生み出すきっかけをつくる。  イチロー
- 壁というのは、できる人にしかやってこない。超えられる可能性がある人にしかやってこない。だから、壁がある時はチャンスだと思っている。  イチロー
- 考える労力を惜しむと前に進むことを止めてしまうことになります。  イチロー
- 何かをしようとした時、失敗を恐れないでやってください。失敗して負けてしまったら、その理由を考えて反省してください。必ず将来の役に立つと思います。  イチロー
- 自分の思ったことをやりつづけることに後悔がありません。もしそれで失敗したとしても後悔は絶対にないはずですから。  イチロー
